# Generated by Django 4.2.7 on 2025-08-02 16:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('uat_tracker_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CaseType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('value', models.CharField(max_length=20, unique=True)),
                ('color', models.CharField(default='#6c757d', help_text='Hex color code', max_length=7)),
                ('order', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Environment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('value', models.CharField(max_length=20, unique=True)),
                ('color', models.CharField(default='#6c757d', help_text='Hex color code', max_length=7)),
                ('order', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Priority',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('value', models.CharField(max_length=20, unique=True)),
                ('color', models.CharField(default='#6c757d', help_text='Hex color code', max_length=7)),
                ('order', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'Priorities',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('value', models.CharField(max_length=20, unique=True)),
                ('color', models.CharField(default='#6c757d', help_text='Hex color code', max_length=7)),
                ('order', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'Statuses',
                'ordering': ['order'],
            },
        ),
        migrations.AlterModelOptions(
            name='uatcase',
            options={'ordering': ['-created_at'], 'permissions': [('can_assign_cases', 'Can assign cases to users'), ('can_view_all_company_cases', 'Can view all company cases')]},
        ),
        migrations.AddField(
            model_name='company',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='company',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='company',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='company_logos/'),
        ),
        migrations.AddField(
            model_name='uatcase',
            name='actual_result',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='uatcase',
            name='case_number',
            field=models.CharField(blank=True, max_length=20, unique=True),
        ),
        migrations.AddField(
            model_name='uatcase',
            name='due_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='uatcase',
            name='expected_result',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='uatcase',
            name='resolved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='uatcase',
            name='sync_error',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_image', models.ImageField(blank=True, null=True, upload_to='profile_images/')),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('department', models.CharField(blank=True, max_length=100)),
                ('job_title', models.CharField(blank=True, max_length=100)),
                ('is_admin', models.BooleanField(default=False)),
                ('can_assign_cases', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employees', to='uat_tracker_app.company')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CreatioConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('base_url', models.URLField(help_text='Creatio instance URL (e.g., https://mycreatio.com)')),
                ('identity_service_url', models.URLField(default='https://myidentityservice.com', help_text='Identity service URL for OAuth (e.g., https://myidentityservice.com)')),
                ('client_id', models.CharField(help_text='OAuth client ID', max_length=100)),
                ('client_secret', models.CharField(help_text='OAuth client secret (encrypted)', max_length=100)),
                ('username', models.CharField(blank=True, help_text='Legacy username (deprecated)', max_length=100)),
                ('password', models.CharField(blank=True, help_text='Legacy password (deprecated)', max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('last_sync', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('company', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='creatio_config', to='uat_tracker_app.company')),
            ],
        ),
        migrations.AlterField(
            model_name='uatcase',
            name='case_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='uat_tracker_app.casetype'),
        ),
        migrations.AlterField(
            model_name='uatcase',
            name='environment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='uat_tracker_app.environment'),
        ),
        migrations.AlterField(
            model_name='uatcase',
            name='priority',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='uat_tracker_app.priority'),
        ),
        migrations.AlterField(
            model_name='uatcase',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='uat_tracker_app.status'),
        ),
    ]
