# Generated by Django 4.2.7 on 2025-08-04 06:24

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('uat_tracker_app', '0002_update_creatio_oauth'),
    ]

    operations = [
        migrations.CreateModel(
            name='DynamicPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(help_text='URL slug for the page', unique=True)),
                ('content', models.TextField(help_text='HTML content for the page')),
                ('is_active', models.BooleanField(default=True)),
                ('show_in_menu', models.BooleanField(default=True, help_text='Show in navigation menu')),
                ('menu_order', models.IntegerField(default=0, help_text='Order in menu (lower numbers first)')),
                ('icon', models.CharField(blank=True, help_text='Font Awesome icon class (e.g., fas fa-home)', max_length=50)),
                ('requires_login', models.BooleanField(default=True, help_text='Require user login to access')),
                ('allowed_roles', models.CharField(blank=True, help_text='Comma-separated roles (admin,manager,user) - leave blank for all', max_length=100)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['menu_order', 'title'],
            },
        ),
        migrations.CreateModel(
            name='DynamicWidget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('widget_type', models.CharField(choices=[('stat', 'Statistics Card'), ('chart', 'Chart Widget'), ('table', 'Data Table'), ('custom', 'Custom HTML')], default='stat', max_length=20)),
                ('content', models.TextField(help_text='Widget content (HTML/JSON config)')),
                ('css_classes', models.CharField(blank=True, help_text='Additional CSS classes', max_length=200)),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.IntegerField(default=0)),
                ('width', models.CharField(default='col-md-6', help_text='Bootstrap column class (e.g., col-md-6, col-lg-4)', max_length=20)),
                ('allowed_roles', models.CharField(blank=True, help_text='Comma-separated roles - leave blank for all', max_length=100)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'ordering': ['order', 'title'],
            },
        ),
        migrations.CreateModel(
            name='SystemSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=100, unique=True)),
                ('value', models.TextField()),
                ('description', models.TextField(blank=True)),
                ('setting_type', models.CharField(choices=[('text', 'Text'), ('number', 'Number'), ('boolean', 'Boolean'), ('json', 'JSON'), ('color', 'Color'), ('url', 'URL')], default='text', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['key'],
            },
        ),
        migrations.CreateModel(
            name='DynamicMenuItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('url', models.CharField(help_text='URL or route name', max_length=200)),
                ('icon', models.CharField(blank=True, help_text='Font Awesome icon class', max_length=50)),
                ('order', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('requires_login', models.BooleanField(default=True)),
                ('allowed_roles', models.CharField(blank=True, max_length=100)),
                ('open_in_new_tab', models.BooleanField(default=False)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='uat_tracker_app.dynamicmenuitem')),
            ],
            options={
                'ordering': ['order', 'title'],
            },
        ),
    ]
